web: gunicorn pebbling.wsgi:application --bind 127.0.0.1:8000 --workers 3
nginx: nginx -g 'daemon off;'
worker: celery -A pebbling worker --loglevel=info --concurrency=4
beat: celery -A pebbling beat --loglevel=info