web: make migrate_prod && gunicorn pebbling.wsgi:application --bind 0.0.0.0:8000 --workers 3
worker: celery -A pebbling worker --loglevel=info --concurrency=4
beat: celery -A pebbling beat --loglevel=info