# Generated by Django 5.1.6 on 2025-06-30 03:37

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MastodonAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "server_url",
                    models.URLField(max_length=255, verbose_name="Mastodon Server URL"),
                ),
                (
                    "server_name",
                    models.CharField(
                        blank=True,
                        help_text="Display name of the server",
                        max_length=255,
                    ),
                ),
                (
                    "server_description",
                    models.TextField(blank=True, help_text="Server description"),
                ),
                (
                    "access_token",
                    models.TextField(help_text="OAuth access token (encrypted)"),
                ),
                (
                    "account_id",
                    models.CharField(help_text="Mastodon account ID", max_length=50),
                ),
                (
                    "username",
                    models.CharField(help_text="Mastodon username", max_length=255),
                ),
                (
                    "display_name",
                    models.CharField(
                        blank=True, help_text="Mastodon display name", max_length=255
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Account connection enabled/disabled"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mastodon_accounts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name="MastodonTimeline",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "timeline_type",
                    models.CharField(
                        choices=[
                            ("HOME", "Home Timeline"),
                            ("LOCAL", "Local Timeline"),
                            ("PUBLIC", "Public Timeline"),
                            ("HASHTAG", "Hashtag Timeline"),
                            ("LIST", "List Timeline"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "config",
                    models.JSONField(
                        default=dict,
                        help_text="Timeline-specific configuration (e.g., hashtag name, list ID)",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Timeline enabled/disabled"
                    ),
                ),
                (
                    "last_status_id",
                    models.CharField(
                        blank=True,
                        help_text="Last processed Mastodon status ID",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "last_poll_attempt",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp of last poll attempt",
                        null=True,
                    ),
                ),
                (
                    "last_successful_poll",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp of last successful poll",
                        null=True,
                    ),
                ),
                (
                    "consecutive_failures",
                    models.IntegerField(
                        default=0, help_text="Count of consecutive poll failures"
                    ),
                ),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timelines",
                        to="mastodon_integration.mastodonaccount",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
            bases=(models.Model,),
        ),
        migrations.AddIndex(
            model_name="mastodonaccount",
            index=models.Index(
                fields=["user", "is_active"], name="mastodon_in_user_id_a26ea9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="mastodonaccount",
            index=models.Index(
                fields=["server_url"], name="mastodon_in_server__87238f_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="mastodonaccount",
            unique_together={("user", "server_url", "account_id")},
        ),
        migrations.AddIndex(
            model_name="mastodontimeline",
            index=models.Index(
                fields=["account", "is_active"], name="mastodon_in_account_57f9ba_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="mastodontimeline",
            index=models.Index(
                fields=["timeline_type"], name="mastodon_in_timelin_f1ea64_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="mastodontimeline",
            index=models.Index(
                fields=["last_poll_attempt"], name="mastodon_in_last_po_05a8b0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="mastodontimeline",
            index=models.Index(
                fields=["consecutive_failures"], name="mastodon_in_consecu_fa2105_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="mastodontimeline",
            unique_together={("account", "timeline_type", "config")},
        ),
    ]
