# Generated by Django 5.1.6 on 2025-02-13 05:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookmarks", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookmark",
            name="unique_hash",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name="bookmark",
            unique_together={("owner", "unique_hash")},
        ),
    ]
