# Generated by Django 5.1.6 on 2025-02-24 16:59

import pebbling_apps.unfurl.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "bookmarks",
            "0003_alter_bookmark_created_at_alter_bookmark_updated_at_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="bookmark",
            name="unfurl_metadata",
            field=pebbling_apps.unfurl.models.UnfurlMetadataField(
                blank=True, null=True
            ),
        ),
    ]
