# Generated by Django 5.1.6 on 2025-03-06 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarks', '0004_bookmark_unfurl_metadata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookmark',
            name='meta',
        ),
        migrations.AlterField(
            model_name='bookmark',
            name='url',
            field=models.URLField(verbose_name='URL'),
        ),
    ]
