# Generated by Django 5.1.6 on 2025-03-24 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookmarks", "0005_remove_bookmark_meta_alter_bookmark_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookmark",
            name="feed_url",
            field=models.URLField(blank=True, null=True, verbose_name="Feed URL"),
        ),
    ]
