# Generated by Django 5.1.6 on 2025-06-16 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookmarks", "0007_set_feed_url_from_unfurl_metadata"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookmark",
            name="url",
            field=models.URLField(max_length=1024, verbose_name="URL"),
        ),
    ]
