# Generated by Django 5.1.6 on 2025-06-16 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookmarks", "0008_alter_bookmark_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookmark",
            name="url",
            field=models.URLField(max_length=10240, verbose_name="URL"),
        ),
    ]
