# Generated by Django 5.1.6 on 2025-06-25 22:43

from django.db import migrations


def normalize_bookmark_hashes_forward(apps, schema_editor):
    """
    No-op migration. Deduplication is now handled by the dedupe_bookmarks management command.
    """
    pass


def normalize_bookmark_hashes_reverse(apps, schema_editor):
    """
    Reverse migration - no-op since we can't reverse hash normalization
    without losing the ability to detect previously normalized duplicates.
    """
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("bookmarks", "0009_alter_bookmark_url"),
    ]

    # Set atomic=False to allow individual transactions for each bookmark
    atomic = False

    operations = [
        migrations.RunPython(
            normalize_bookmark_hashes_forward,
            normalize_bookmark_hashes_reverse,
        ),
    ]
