# Generated by Django 5.1.6 on 2025-06-29 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookmarks", "0011_importjob"),
    ]

    operations = [
        migrations.AddField(
            model_name="tag",
            name="is_system",
            field=models.BooleanField(
                default=False, help_text="Whether this is a system-managed tag"
            ),
        ),
    ]
