# Generated by Django 5.1.6 on 2025-06-29 17:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookmarks", "0012_add_system_tag_support"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="name",
            field=models.CharField(max_length=64),
        ),
        migrations.AlterUniqueTogether(
            name="tag",
            unique_together={("name", "owner")},
        ),
        migrations.AddIndex(
            model_name="tag",
            index=models.Index(
                fields=["owner", "name"], name="bookmarks_t_owner_i_4fe69b_idx"
            ),
        ),
    ]
