# Generated by Django 5.1.6 on 2025-02-21 01:19

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies: list[str] = []

    operations = [
        migrations.CreateModel(
            name="Feed",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("url", models.URLField(max_length=2048, unique=True)),
                ("title", models.CharField(blank=True, max_length=200, null=True)),
                ("newest_item_date", models.DateTimeField(blank=True, null=True)),
                ("disabled", models.BooleanField(default=False)),
                ("etag", models.CharField(blank=True, max_length=256, null=True)),
                (
                    "modified",
                    models.CharField(
                        blank=True, max_length=256, null=True, unique=True
                    ),
                ),
            ],
            options={
                "ordering": ["-newest_item_date"],
                "indexes": [
                    models.Index(
                        fields=["newest_item_date"],
                        name="feeds_feed_newest__43603d_idx",
                    ),
                    models.Index(
                        fields=["disabled"], name="feeds_feed_disable_5927a0_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="FeedItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("guid", models.CharField(max_length=2048)),
                ("date", models.DateTimeField()),
                ("link", models.URLField(max_length=2048)),
                ("title", models.CharField(max_length=500)),
                ("summary", models.TextField(blank=True)),
                ("description", models.TextField(blank=True)),
                (
                    "last_seen_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("first_seen_at", models.DateTimeField(auto_now_add=True)),
                (
                    "feed",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="feeds.feed",
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
                "indexes": [
                    models.Index(fields=["guid"], name="feeds_feedi_guid_b991ee_idx"),
                    models.Index(fields=["date"], name="feeds_feedi_date_20fb3e_idx"),
                    models.Index(
                        fields=["last_seen_at"], name="feeds_feedi_last_se_e37875_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("feed", "guid"), name="unique_feed_item"
                    )
                ],
            },
        ),
    ]
