# Generated by Django 5.1.6 on 2025-02-22 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feeds", "0003_feeditem_json"),
    ]

    operations = [
        migrations.AddField(
            model_name="feed",
            name="json",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
