# Generated by Django 5.1.6 on 2025-06-16 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feeds", "0004_feed_json"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feed",
            name="title",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
