# Generated by Django 5.1.6 on 2025-06-24 04:18

from django.db import migrations


def create_poll_feeds_schedule(apps, schema_editor):
    """Create initial periodic task for polling feeds every 30 minutes."""
    PeriodicTask = apps.get_model('django_celery_beat', 'PeriodicTask')
    IntervalSchedule = apps.get_model('django_celery_beat', 'IntervalSchedule')
    
    # Create or get 30 minute interval
    schedule, _ = IntervalSchedule.objects.get_or_create(
        every=30,
        period='minutes',
    )
    
    # Create the periodic task
    PeriodicTask.objects.get_or_create(
        name='Poll All Feeds',
        defaults={
            'task': 'pebbling_apps.feeds.tasks.poll_all_feeds',
            'interval': schedule,
            'enabled': True,
            'description': 'Polls all RSS/Atom feeds for new content',
            'kwargs': '{"priority": 3}',  # JSON string for task kwargs
        }
    )


def remove_poll_feeds_schedule(apps, schema_editor):
    """Remove the poll feeds periodic task."""
    PeriodicTask = apps.get_model('django_celery_beat', 'PeriodicTask')
    PeriodicTask.objects.filter(name='Poll All Feeds').delete()


class Migration(migrations.Migration):

    dependencies = [
        ("feeds", "0005_alter_feed_title"),
        ("django_celery_beat", "0018_improve_crontab_helptext"),
    ]

    operations = [
        migrations.RunPython(
            create_poll_feeds_schedule,
            remove_poll_feeds_schedule,
        ),
    ]
