# Generated by Django 5.1.6 on 2025-06-24 06:00

from django.db import migrations


def fix_task_name(apps, schema_editor):
    """Fix the task name from full module path to registered name."""
    PeriodicTask = apps.get_model('django_celery_beat', 'PeriodicTask')
    
    # Update the task name if it exists with the wrong name
    PeriodicTask.objects.filter(
        name='Poll All Feeds',
        task='pebbling_apps.feeds.tasks.poll_all_feeds'
    ).update(task='poll_all_feeds')


def revert_task_name(apps, schema_editor):
    """Revert to full module path (for rollback)."""
    PeriodicTask = apps.get_model('django_celery_beat', 'PeriodicTask')
    
    PeriodicTask.objects.filter(
        name='Poll All Feeds',
        task='poll_all_feeds'
    ).update(task='pebbling_apps.feeds.tasks.poll_all_feeds')


class Migration(migrations.Migration):

    dependencies = [
        ("feeds", "0006_add_poll_feeds_periodic_task"),
        ("django_celery_beat", "0018_improve_crontab_helptext"),
    ]

    operations = [
        migrations.RunPython(fix_task_name, revert_task_name),
    ]
