# Generated by Django 5.1.6 on 2025-06-28

from django.db import migrations


def fix_poll_feeds_priority(apps, schema_editor):
    """Remove incorrect kwargs from Poll All Feeds periodic task."""
    PeriodicTask = apps.get_model("django_celery_beat", "PeriodicTask")
    
    try:
        task = PeriodicTask.objects.get(name="Poll All Feeds")
        # Remove the kwargs that were causing the error
        task.kwargs = "{}"
        task.save()
    except PeriodicTask.DoesNotExist:
        pass


def revert_poll_feeds_priority(apps, schema_editor):
    """Revert to previous state (for rollback)."""
    PeriodicTask = apps.get_model("django_celery_beat", "PeriodicTask")
    
    try:
        task = PeriodicTask.objects.get(name="Poll All Feeds")
        task.kwargs = '{"priority": 3}'
        task.save()
    except PeriodicTask.DoesNotExist:
        pass


class Migration(migrations.Migration):

    dependencies = [
        ("feeds", "0007_fix_poll_feeds_task_name"),
        ("django_celery_beat", "0018_improve_crontab_helptext"),
    ]

    operations = [
        migrations.RunPython(
            fix_poll_feeds_priority,
            revert_poll_feeds_priority,
        ),
    ]