web: su -c "gunicorn pebbling.wsgi:application --bind 127.0.0.1:8001 --workers 3" django
nginx: nginx -c /etc/nginx/nginx.conf -g 'daemon off; error_log /dev/stderr info;'
worker: su -c "celery -A pebbling worker --loglevel=info --concurrency=4" django
beat: su -c "celery -A pebbling beat --loglevel=info" django