# Generated by Django 5.1.6 on 2025-06-29 07:24

import django.db.models.deletion
import django.utils.timezone
import django_prometheus.models
import pebbling_apps.unfurl.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("bookmarks", "0012_add_system_tag_support"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InboxItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("url", models.URLField(max_length=10240, verbose_name="URL")),
                ("unique_hash", models.CharField(max_length=255)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "unfurl_metadata",
                    pebbling_apps.unfurl.models.UnfurlMetadataField(
                        blank=True, null=True
                    ),
                ),
                (
                    "feed_url",
                    models.URLField(blank=True, null=True, verbose_name="Feed URL"),
                ),
                (
                    "source",
                    models.CharField(
                        help_text="Source of this inbox item", max_length=255
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(
                        blank=True, related_name="inbox_items", to="bookmarks.tag"
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["owner", "created_at"],
                        name="inbox_inbox_owner_i_36b60a_idx",
                    ),
                    models.Index(
                        fields=["source"], name="inbox_inbox_source_59bf97_idx"
                    ),
                    models.Index(
                        fields=["owner", "source"],
                        name="inbox_inbox_owner_i_3b9aaf_idx",
                    ),
                ],
                "unique_together": {("owner", "unique_hash")},
            },
            bases=(
                django_prometheus.models.ExportModelOperationsMixin("inbox_item"),
                models.Model,
            ),
        ),
    ]
