# Generated by Django 5.1.6 on 2025-06-30 04:47

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inbox", "0001_initial_inbox_models"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="inboxitem",
            unique_together={("owner", "unique_hash", "source")},
        ),
    ]
