# Generated by Django 5.1.6 on 2025-07-03 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inbox", "0002_update_inbox_item_unique_constraint"),
    ]

    operations = [
        migrations.AddField(
            model_name="inboxitem",
            name="metadata",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Source-specific metadata (e.g., Mastodon status ID, feed item ID)",
            ),
        ),
    ]
