# Generated by Django 5.1.6 on 2025-07-03 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inbox", "0003_add_metadata_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="inboxitem",
            name="source_type",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Type of source (e.g., 'mastodon', 'feed', 'manual')",
                max_length=50,
            ),
        ),
    ]
