name: pebbling-club

x-django-environment: &django-env
  DJANGO_SETTINGS_MODULE: pebbling.settings
  DEBUG: ${DEBUG:-False}
  SECRET_KEY: ${SECRET_KEY:-your-secret-key-here-1234567890}
  ALLOWED_HOSTS: ${ALLOWED_HOSTS:-localhost,127.0.0.1,web}
  CSRF_TRUSTED_ORIGINS: ${CSRF_TRUSTED_ORIGINS:-http://localhost:8000,http://127.0.0.1:8000}
  DATABASE_URL: ${DATABASE_URL:-postgres://pebbling:pebbling_password@postgres:5432/pebbling}
  CELERY_BROKER_URL: ${CELERY_BROKER_URL:-redis://redis:6379/0}
  REDIS_URL: ${REDIS_URL:-redis://redis:6379/1}
  DJANGO_SQLITE_MULTIPLE_DB: ${DJANGO_SQLITE_MULTIPLE_DB:-false}
  LOG_LEVEL: ${LOG_LEVEL:-INFO}
  ALLOW_USER_REGISTRATION: ${ALLOW_USER_REGISTRATION:-true}
  # Nginx authentication (use htpasswd to generate hashes)
  FLOWER_PASSWORD_HASH: ${FLOWER_PASSWORD_HASH:-}
  METRICS_PASSWORD_HASH: ${METRICS_PASSWORD_HASH:-}

x-django-base: &django-base
  image: lmorchard/pebbling-club:latest
  environment:
    <<: *django-env
  restart: unless-stopped
  logging:
    driver: "json-file"
    options:
      max-size: "10m"
      max-file: "3"

services:
  # This service is only for building the image
  django-builder:
    image: lmorchard/pebbling-club:latest
    build:
      context: ../../
      dockerfile: docker/compose/Dockerfile
    command: echo "Build complete"
    profiles:
      - build-only

  # PostgreSQL Database
  postgres:
    image: postgres:16-alpine
    volumes:
      - ../../data/postgresql:/var/lib/postgresql/data:z
    environment:
      - POSTGRES_DB=pebbling
      - POSTGRES_USER=pebbling
      - POSTGRES_PASSWORD=pebbling_password
      - POSTGRES_INITDB_ARGS=--auth-host=scram-sha-256 --auth-local=scram-sha-256
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pebbling"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  # Redis for Celery broker
  redis:
    image: redis:7-alpine
    command: redis-server --save "" --appendonly no --maxmemory ${REDIS_MAXMEMORY:-256mb} --maxmemory-policy ${REDIS_MAXMEMORY_POLICY:-allkeys-lru}
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  # Django web application
  web:
    <<: *django-base
    volumes:
      - static_files:/app/static
      - media_files:/app/media
      - app_data:/app/data
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

  # Celery worker
  celery_worker:
    <<: *django-base
    command: celery -A pebbling worker --loglevel=info --autoscale=${CELERY_AUTOSCALE_MIN:-4},${CELERY_AUTOSCALE_MAX:-16} --max-memory-per-child=${CELERY_MAX_MEMORY_PER_CHILD:-200000}
    volumes:
      - app_data:/app/data
    depends_on:
      - redis
      - postgres
    environment:
      <<: *django-env
      CELERY_AUTOSCALE_MAX: ${CELERY_AUTOSCALE_MAX:-32}
      CELERY_AUTOSCALE_MIN: ${CELERY_AUTOSCALE_MIN:-4}

  # Celery Flower (monitoring) - minimal env vars
  celery_flower:
    image: lmorchard/pebbling-club:latest
    command: celery -A pebbling flower --port=5555 --url-prefix=flower
    depends_on:
      - redis
    environment:
      CELERY_BROKER_URL: ${CELERY_BROKER_URL:-redis://redis:6379/0}
      LOG_LEVEL: ${LOG_LEVEL:-INFO}

  # Celery beat for scheduled tasks
  celery_beat:
    <<: *django-base
    command: celery -A pebbling beat --loglevel=info
    volumes:
      - app_data:/app/data
    depends_on:
      - redis
      - postgres

  # Nginx web server
  nginx:
    image: nginx:1.25-alpine
    ports:
      - "8000:8000"
    volumes:
      - static_files:/app/static:ro
      - media_files:/app/media:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - web
    environment:
      FORWARDED_PROTO: ${FORWARDED_PROTO:-http}
      FLOWER_PASSWORD_HASH: ${FLOWER_PASSWORD_HASH:-}
      METRICS_PASSWORD_HASH: ${METRICS_PASSWORD_HASH:-}
    command: |
      sh -c "
        # Create htpasswd files from environment variables
        mkdir -p /etc/nginx
        
        if [ -n \"$$FLOWER_PASSWORD_HASH\" ]; then
          echo \"admin:$$FLOWER_PASSWORD_HASH\" > /etc/nginx/.htpasswd_flower
          echo '✓ Created Flower authentication for user admin'
        else
          echo '⚠️  FLOWER_PASSWORD_HASH not set - Flower UI will be inaccessible'
          echo 'Generate with: htpasswd -nbB admin your_password'
        fi
        
        if [ -n \"$$METRICS_PASSWORD_HASH\" ]; then
          echo \"prometheus:$$METRICS_PASSWORD_HASH\" > /etc/nginx/.htpasswd_metrics
          echo '✓ Created metrics authentication for user prometheus'
        else
          echo '⚠️  METRICS_PASSWORD_HASH not set - metrics endpoints will be inaccessible'
          echo 'Generate with: htpasswd -nbB prometheus your_password'
        fi
        
        # Start nginx
        exec nginx -g 'daemon off;'
      "
    restart: unless-stopped

volumes:
  static_files:
  media_files:
  app_data:
