#!/bin/bash
set -e

# Create additional databases for the application
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE DATABASE ${POSTGRES_DB}_feeds;
    CREATE DATABASE ${POSTGRES_DB}_celery;
    CREATE DATABASE ${POSTGRES_DB}_cache;
    
    GRANT ALL PRIVILEGES ON DATABASE ${POSTGRES_DB} TO ${POSTGRES_USER};
    GRANT ALL PRIVILEGES ON DATABASE ${POSTGRES_DB}_feeds TO ${POSTGRES_USER};
    GRANT ALL PRIVILEGES ON DATABASE ${POSTGRES_DB}_celery TO ${POSTGRES_USER};
    GRANT ALL PRIVILEGES ON DATABASE ${POSTGRES_DB}_cache TO ${POSTGRES_USER};
EOSQL
